### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Timithy-L** [kerwincui/wumei-smart#1]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/53697384/154609644-5a5fb642-6776-4277-91ba-4d8064e332ca.png">

**Comment by kerwincui** [comment]
项目还在开发中，后续会有教程。另外提供的截图只能看到是auth模块报错，可以仔细看下报错信息，排查问题

**Comment by Timithy-L** [comment]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/53697384/154611345-63b94fcb-cf2f-4ef0-b687-20fa9f68e83e.png">

**Comment by kerwincui** [comment]
new version released
