### ISSUE TITLE
想咨询一下，下个版本什么时候发布？

### ISSUE THREAD

**Issue by kami0314** [kerwincui/wumei-smart#2]

**Comment by kerwincui** [comment]
三月份会有个预览版

**Comment by kami0314** [comment]
> 三月份会有个预览版

预览版本中会有数据存储相关的吗？

**Comment by kerwincui** [comment]
有的，目前是mysql存储

**Comment by kami0314** [comment]
> 有的，目前是mysql存储

我想表达的不是设备管理这些数据存储，我想学习采集的历史数据怎么和物模型关联并且存储。

**Comment by kerwincui** [comment]
物模型存储在mysql和redis里面，产品下的物模型标识符是唯一的，通过标识符关联

**Comment by kami0314** [comment]
> 

采集到的历史数据，现在没有存到mysql吧？是打算后续存储到TDengine中吗？

**Comment by kerwincui** [comment]
mysql存储，后续扩展到时序数据库

**Comment by kami0314** [comment]
> mysql存储，后续扩展到时序数据库

收到，谢谢。
