### ISSUE TITLE
会有视频教程吗?

### ISSUE THREAD

**Issue by KinG-Z-L** [kerwincui/wumei-smart#5]

**Comment by kerwincui** [comment]
目前只有文档

**Comment by KinG-Z-L** [comment]
> 目前只有文档

请问，我在服务器上建站成功了，看了下数据库里的管理员密码用Bcrypt加密了的，能否告知一下明文？我在技术文档里好像没翻到管理员密码。

**Comment by KinG-Z-L** [comment]
请问，我在服务器上建站成功了，看了下数据库里的管理员密码用Bcrypt加密了的，能否告知一下明文？我在技术文档里好像没翻到管理员密码。

**Comment by kerwincui** [comment]
文档里面有的，账号密码是：admin     admin123

**Comment by KinG-Z-L** [comment]
> 文档里面有的，账号密码是：admin admin123

收到，十分感谢您的回复！
