### ISSUE TITLE
说找不到app.jar

### ISSUE THREAD

**Issue by Zhangtiande** [kerwincui/wumei-smart#6]
我把wumei-admin打包过去了，
![image](https://user-images.githubusercontent.com/61372351/163166961-0c516d2d-6457-4a74-9b9e-617128945dff.png)
权限应该没问题
![image](https://user-images.githubusercontent.com/61372351/163167018-c5658f25-a266-4bf4-95aa-f864684e0963.png)

**Comment by kerwincui** [comment]
项目有制作好的镜像可以直接使用。估计是jar包没有拷贝进去。你去容器里面看下对应目录是否有app.jar文件。

**Comment by Zhangtiande** [comment]
好的，数据卷忘记挂载上了
